# Example - 1

# Base Image - FROM  
FROM ubuntu:latest

# Which command would be executed?
CMD ["/bin/echo", "Hello World - CMD 1\n"]
CMD ["/bin/echo", "Hello World - CMD 2\n"]
CMD ["/bin/echo", "Hello World - CMD 3\n"]
CMD ["/bin/echo", "Hello World - CMD 4\n"]
CMD ["/bin/echo", "Hello World - CMD 5\n"]